# Generated by Django 3.2.9 on 2022-02-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
